# Generated by Django 4.1 on 2024-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
