# Generated by Django 4.1 on 2024-12-15 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0003_remove_cours_enseignant_cours_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 12, 50, 23, 43042, tzinfo=datetime.timezone.utc)),
        ),
    ]
