# Generated by Django 4.1 on 2024-12-17 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0008_alter_cours_date_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours'},
        ),
        migrations.AlterField(
            model_name='cours',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 8, 49, 8, 569553, tzinfo=datetime.timezone.utc)),
        ),
    ]
